#ifdef BOARD_AB_SMARTHOUSE_BPS_REG6
    #define DEVICE_ID "AB-BPS-RED"
    #define HARDWARE_NAME "AB-BPS-RED"
    #define DEVICE_NAME "AB-SmartHouse Bus Power Supply 1280 mA Redundant, 6 TE"

    #define INFO_LED_PIN 24
    #define INFO_LED_PIN_ACTIVE_ON HIGH
    #define PROG_LED_PIN 23
    #define PROG_LED_PIN_ACTIVE_ON HIGH
    #define PROG_BUTTON_PIN 9
    #define PROG_BUTTON_PIN_INTERRUPT_ON FALLING

    #define KNX_UART_NUM 0
    #define KNX_UART_TX_PIN 16
    #define KNX_UART_RX_PIN 17
    #define SAVE_INTERRUPT_PIN 0

    #define OPENKNX_BPS_PWR1_CHECK_PIN 29
    #define OPENKNX_BPS_PWR1_SWITCH_ON_PIN 27
    #define OPENKNX_BPS_PWR1_ALERT_PIN 13
    #define OPENKNX_BPS_PWR2_CHECK_PIN 26
    #define OPENKNX_BPS_PWR2_SWITCH_ON_PIN 28
    #define OPENKNX_BPS_PWR2_ALERT_PIN 12
    #define OPENKNX_BPS_PWR_CHECK_FACTOR 10.999371
    #define OPENKNX_BPS_PWR_SWITCH_ACTIVE_ON HIGH

    #define OPENKNX_BPS_STATUS_BUS 0x0100
    #define OPENKNX_BPS_STATUS_TMP 0x0101
    #define OPENKNX_BPS_STATUS_TRC 0x0102
    #define OPENKNX_BPS_STATUS_DEV 0x0103
    #define OPENKNX_BPS_STATUS_PW1 0x0104
    #define OPENKNX_BPS_STATUS_PW2 0x0105
    #define OPENKNX_BPS_STATUS_MAX 0x0106
    #define OPENKNX_BPS_STATUS_RST 0x0107
    #define OPENKNX_BPS_STATUS_ACTIVE_ON HIGH
    #define OPENKNX_BPS_SWITCH_RST 0x0108
    #define OPENKNX_BPS_SWITCH_ACTIVE_ON LOW

    #define OPENKNX_BPS_CURRENT_KNX_INA_ADDR 0x40
    #define OPENKNX_BPS_CURRENT_KNX_INA_SHUNT 0.01
    #define OPENKNX_BPS_CURRENT_AUX_INA_ADDR 0x41
    #define OPENKNX_BPS_CURRENT_AUX_INA_SHUNT 0.01

    #define OPENKNX_BPS_TEMPSENS_ADDR 0x48

    #define OPENKNX_GPIO_NUM 1
    #define OPENKNX_GPIO_TYPES OPENKNX_GPIO_T_TCA9555
    #define OPENKNX_GPIO_ADDRS 0x20
    #define OPENKNX_GPIO_INTS 25

    #define OPENKNX_GPIO_WIRE Wire1
    #define OPENKNX_GPIO_SDA 6
    #define OPENKNX_GPIO_SCL 7
    #define OPENKNX_GPIO_CLOCK 400000
#endif