#pragma once

#define MAIN_Version "8823f41"
#define KNX_Version "2.2.2+288b299"
#define MODULE_BusPowerSupply_Version "0.1.0+1e432d3"
#define MODULE_BusPowerSupply_Version_Major 0
#define MODULE_BusPowerSupply_Version_Minor 1
#define MODULE_BusPowerSupply_Version_Revision 0
#define MODULE_BusPowerSupply_ETS 1
#define MODULE_Common_Version "1.6.0+86b8cad"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 6
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 22
#define MODULE_LogicModule_Version "3.8.0+55beacc"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 8
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 56
#define MODULE_FileTransferModule_Version "0.1.4+3a96b4e"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 4
#define MODULE_FileTransferModule_ETS 1
#define MODULE_FunctionBlocks_Version "0.6.0+7663283"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 6
#define MODULE_FunctionBlocks_Version_Revision 0
#define MODULE_FunctionBlocks_ETS 6
